name: Tests

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: cargo-build-${{ hashFiles('Cargo.toml') }}
      - name: Install system dependencies
        run: sudo apt-get install libasound2-dev libudev-dev
      - name: Run tests
        run: cargo test --all-features

  rustChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            server/target/
          key: cargo-build-${{ hashFiles('Cargo.toml') }}
      - name: Install system dependencies
        run: sudo apt-get install libasound2-dev libudev-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: rustfmt
        run: cargo fmt --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -A deprecated -D warnings